{% set name = "automan" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ef29e1f7d6133af9c428ab8e549da2101bccdd0cb6fb9a2caa48c70af8de226

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - execnet
    - pip
    - psutil
    - python {{ python_min }}
    - mock
  run:
    - execnet
    - psutil
    - python >={{ python_min }}

test:
  imports:
    - automan
    - automan.tests
  requires:
    - pytest
    - mock
    - python {{ python_min }}
  source_files:
    - automan/tests/*
  commands:
    - pytest --pyargs automan

about:
  home: https://github.com/pypr/automan
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'automan: a simple automation framework'


extra:
  recipe-maintainers:
    - rishi9699
    
